name: The Mega Plush
favicon: null
layout_spectrum: 0.59589
typography_spectrum: 0.05494
title: The Mega Plush
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#3d3d38'
    - '#fbfbfc'
    - '#6a7073'
    - '#a6b1ae'
  brandStrength: 0.043697873363271356
  lightness: 0.2779514561407268
  saturation: 0.7886522409971803
  rhythmicContrast: 0.75
purpose: []
