name: The Mega Plush
favicon: null
layout_spectrum: 0.9105296663474292
typography_spectrum: 0.01882658712565899
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.043697873363271356
  lightness: 0.2779514561407268
  saturation: 0.7886522409971803
  rhythmicContrast: 0.08831476955674589
purpose: []
